"""empty message

Revision ID: 253133fdc11c
Revises: 946ebafa5392
Create Date: 2024-04-26 09:36:55.706052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253133fdc11c'
down_revision: Union[str, None] = '946ebafa5392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('fouls_committed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'fouls_committed')
    # ### end Alembic commands ###
