"""empty message

Revision ID: 946ebafa5392
Revises: cf10e119be85
Create Date: 2024-04-25 14:31:10.766311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946ebafa5392'
down_revision: Union[str, None] = 'cf10e119be85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('substitute', sa.Boolean(), nullable=True),
    sa.Column('captain', sa.Boolean(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('goals_total', sa.Integer(), nullable=True),
    sa.Column('goals_conceded', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('saves', sa.Integer(), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=True),
    sa.Column('key_passes', sa.Integer(), nullable=True),
    sa.Column('passing_accuracy', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('total_duels', sa.Integer(), nullable=False),
    sa.Column('duels_won', sa.Integer(), nullable=False),
    sa.Column('dribble_attempts', sa.Integer(), nullable=True),
    sa.Column('successful_dribbles', sa.Integer(), nullable=True),
    sa.Column('fouls_drawn', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('penalties_won', sa.Integer(), nullable=True),
    sa.Column('penalties_commited', sa.Integer(), nullable=True),
    sa.Column('penalties_scored', sa.Integer(), nullable=True),
    sa.Column('penalties_missed', sa.Integer(), nullable=True),
    sa.Column('penalties_saved', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistic_fixture_id'), 'statistic', ['fixture_id'], unique=False)
    op.create_index(op.f('ix_statistic_player_id'), 'statistic', ['player_id'], unique=False)
    op.create_index(op.f('ix_statistic_team_id'), 'statistic', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_team_id'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_player_id'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_fixture_id'), table_name='statistic')
    op.drop_table('statistic')
    # ### end Alembic commands ###
