"""empty message

Revision ID: c270b48a6d95
Revises: 253133fdc11c
Create Date: 2024-04-26 10:09:27.030956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c270b48a6d95'
down_revision: Union[str, None] = '253133fdc11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'yellow_cards')
    op.drop_column('statistic', 'fouls_committed')
    op.drop_column('statistic', 'duels_won')
    op.drop_column('statistic', 'total_duels')
    op.drop_column('statistic', 'red_cards')
    op.drop_column('statistic', 'captain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistic', sa.Column('captain', sa.BOOLEAN(), nullable=False))
    op.add_column('statistic', sa.Column('red_cards', sa.INTEGER(), nullable=False))
    op.add_column('statistic', sa.Column('total_duels', sa.INTEGER(), nullable=False))
    op.add_column('statistic', sa.Column('duels_won', sa.INTEGER(), nullable=False))
    op.add_column('statistic', sa.Column('fouls_committed', sa.INTEGER(), nullable=False))
    op.add_column('statistic', sa.Column('yellow_cards', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
